# Тензоры

In [3]:
import torch

x = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [4]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [5]:
torch.zeros((1, 2)), torch.ones((1, 2))

(tensor([[0., 0.]]), tensor([[1., 1.]]))

In [6]:
torch.zeros((1, 2)) +torch.ones((1, 2))

tensor([[1., 1.]])

In [7]:
torch.rand(1).item()

0.49561625719070435

Тензоры «живут» в центральном или графическом процессоре и могут быть скопированы с помощью функции to():

In [ ]:
cpu_tensor = torch.rand(2)
print(cpu_tensor.device)

gpu_tensor = cpu_tensor.to("cuda")
print(gpu_tensor.device)

## Операции

In [11]:
tensor = torch.rand(2, 2)
print(tensor)

tensor([[0.2843, 0.1694],
        [0.4114, 0.8752]])


In [12]:
tensor.max(), tensor.max().item()

(tensor(0.8752), 0.8751785159111023)

Смена типа данных

In [14]:
long_tensor = torch.tensor([[0, 1, 0], [1, 1, 1], [0, 0, 0]])
long_tensor.type()

'torch.LongTensor'

In [15]:
float_tensor = torch.tensor([[0, 1, 0], [1, 1, 1], [0, 0, 0]]).to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

Большинство функций, которые работают от тензоров и возвращают тензор, создают новый тензор для хранения результата. Однако если вы хотите сэкономить память, посмотрите, определена ли функция in-place, имя которой должно совпадать с именем исходной функции, но с добавлением нижнего подчеркивания (_).

In [16]:
tensor = torch.rand(2, 2)
tensor.log2(), tensor

(tensor([[-0.6312, -0.0433],
         [-0.8961, -0.8919]]),
 tensor([[0.6456, 0.9704],
         [0.5373, 0.5389]]))

In [17]:
tensor.log2_(), tensor

(tensor([[-0.6312, -0.0433],
         [-0.8961, -0.8919]]),
 tensor([[-0.6312, -0.0433],
         [-0.8961, -0.8919]]))

Изменение формы

In [18]:
flat_tensor = torch.rand(784)
flat_tensor.shape

torch.Size([784])

In [19]:
tensor = flat_tensor.reshape(1, 28, 28)
tensor.shape

torch.Size([1, 28, 28])

Изменение размеров

In [20]:
tensor = torch.rand(640, 480, 3)
tensor.shape

torch.Size([640, 480, 3])

In [22]:
tensor2 = tensor.permute(2, 0, 1)
tensor2.shape

torch.Size([3, 640, 480])