In [1]:
import tensorflow as tf

Rank 0 tensor creating

In [3]:
r1 = tf.constant(1, dtype=tf.int16) # zero dimension
print(r1)

tf.Tensor(1, shape=(), dtype=int16)


In [4]:
r2 = tf.constant(2, tf.int16, name='my_scalar')
print(r2)

tf.Tensor(2, shape=(), dtype=int16)


In [5]:
r3 = tf.constant(1.23, tf.float32, name='my_float')
print(r3)

tf.Tensor(1.23, shape=(), dtype=float32)


In [6]:
r4 = tf.constant('string', tf.string, name='my_string')
print(r4)

tf.Tensor(b'string', shape=(), dtype=string)


Rank 1 tensor creating

In [7]:
r1_vector = tf.constant([1, 2, 3], tf.int16)
print(r1_vector)

tf.Tensor([1 2 3], shape=(3,), dtype=int16)


In [8]:
r2_vector = tf.constant([True, False, False], tf.bool)
print(r2_vector)

tf.Tensor([ True False False], shape=(3,), dtype=bool)


Rank3 tensors creating

In [9]:
r3_matrix = tf.constant([ [[1, 2],
                           [3, 4],
                           [5, 6]] ], tf.int16)
print(r3_matrix)
print('Shape of r3_matrix is ', r3_matrix.shape)
print('r3_matriz data type is ', r3_matrix.dtype)

tf.Tensor(
[[[1 2]
  [3 4]
  [5 6]]], shape=(1, 3, 2), dtype=int16)
Shape of r3_matrix is  (1, 3, 2)
r3_matriz data type is  <dtype: 'int16'>


Creation of ones and zeros matrices

In [10]:
print(tf.zeros(10))
print(tf.ones([2, 2]))
print(tf.eye(3))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


Data type transformation

In [11]:
print('\ndata transformation')
print('r2 tensor is', r2, ' dtype is ', r2.dtype)
r2_toint = tf.cast(r2, dtype=tf.int32)
print('transform to int:', r2_toint, ' dtype is ', r2_toint.dtype)


data transformation
r2 tensor is tf.Tensor(2, shape=(), dtype=int16)  dtype is  <dtype: 'int16'>
transform to int: tf.Tensor(2, shape=(), dtype=int32)  dtype is  <dtype: 'int32'>


Math operations

In [12]:
x = tf.constant(2.0, dtype=tf.float32)
print('sqrt of ', x, 'is ', tf.sqrt(x))

sqrt of  tf.Tensor(2.0, shape=(), dtype=float32) is  tf.Tensor(1.4142135, shape=(), dtype=float32)


In [13]:
y = tf.constant([1.0, 2.0], dtype=tf.float32)
z = tf.constant([3.0, 4.0], dtype=tf.float32)
print('Sum of ', y, 'and ', z, ' is ', tf.add(y, z))

Sum of  tf.Tensor([1. 2.], shape=(2,), dtype=float32) and  tf.Tensor([3. 4.], shape=(2,), dtype=float32)  is  tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [14]:
print('Subtract of ', y, 'and ', z, ' is ', tf.subtract(y, z))

Subtract of  tf.Tensor([1. 2.], shape=(2,), dtype=float32) and  tf.Tensor([3. 4.], shape=(2,), dtype=float32)  is  tf.Tensor([-2. -2.], shape=(2,), dtype=float32)


In [15]:
y = tf.constant([[1, 2]])
z = tf.constant([[3], [4]])
print('Multiplication of ', y, 'and ', z, ' is ', tf.multiply(y, z))
# tf.div(), tf.pow(a, b) ...

Multiplication of  tf.Tensor([[1 2]], shape=(1, 2), dtype=int32) and  tf.Tensor(
[[3]
 [4]], shape=(2, 1), dtype=int32)  is  tf.Tensor(
[[3 6]
 [4 8]], shape=(2, 2), dtype=int32)


Variables creation

In [16]:
x = tf.constant([[1, 2], [3, 4]])
var = tf.Variable(x)
print('\nInitialized variable: ', var)
print('Assigned variable:', var.assign([[3, 4], [5, 6]]))


Initialized variable:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
Assigned variable: <tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6]])>
