In [1]:
import tensorflow as tf
import numpy as np

# BASICS
Create 0D tensor (int32)

In [2]:
rank_0_tensor = tf.constant(4)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

Create 1D-vector

In [3]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

Create 2D matrix with specific dtype

In [4]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float16)>

Tensor to numpy array

In [5]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.]], dtype=float16)

Tensor math operations

In [6]:
print('\n\nMath operations\n\n')
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print('a+b = ', tf.add(a, b), '\n')
print('element multiply: ', tf.multiply(a, b), '\n')
print('matrix multiply: ', tf.matmul(a, b), '\n')



Math operations


a+b =  tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

element multiply:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

matrix multiply:  tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [7]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [8]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print('Largest value: ', tf.reduce_max(c))

Largest value:  tf.Tensor(10.0, shape=(), dtype=float32)


In [9]:
print('The index of the largest value: ', tf.argmax(c))

The index of the largest value:  tf.Tensor([1 0], shape=(2,), dtype=int64)


In [12]:
print('Compute the softmax: ', tf.nn.softmax(c))

Compute the softmax:  tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


Shapes

In [13]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


Indexing

In [15]:
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy())

Second row: [3. 4.]
Second column: [2. 4.]
Last row: [3. 4.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]]


Shapes manipulation

In [16]:
x = tf.constant([[1], [2], [3]])
print(x.shape)
print(x.shape.as_list())
reshaped = tf.reshape(x, [1, 3])
print('Resyaped 1x3: ', reshaped, ' shape: ', reshaped.shape)
print('Automatically calculate number of elements with reshape: ', tf.reshape(rank_2_tensor, [-1]))

(3, 1)
[3, 1]
Resyaped 1x3:  tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)  shape:  (1, 3)
Automatically calculate number of elements with reshape:  tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


Sparse tensors

In [18]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 



In [19]:
# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


# Variables

In [20]:
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)
my_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [21]:
tf.Variable([False, False, False, True])

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>

In [22]:
tf.Variable([5 + 4j, 6 + 1j])

<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>

In [23]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


Assign variables

In [26]:
a = tf.Variable([2.0, 3.0], name='my var')
print('a: ', a)

a:  <tf.Variable 'my var:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>


In [27]:
a.assign([1, 2])
print('new a: ', a)

new a:  <tf.Variable 'my var:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
