# Гаусовские модели

Построение гауссианов по неразмеченным данным (diagonal, spherical, tied and full covariance matrices supported), covariance_type{‘full’, ‘tied’, ‘diag’, ‘spherical’}, default=’full’

Предсказывает, к какому гауссиану относится новый объект по плотности вероятности.

In [2]:
import numpy as np
from sklearn.mixture import GaussianMixture
X = np.array([[1, 2], [1, 4], [1, 0], [10, 2], [10, 4], [10, 0]])
gm = GaussianMixture(n_components=2, random_state=0).fit(X)
gm.means_


gm.predict([[0, 0], [12, 3]])

array([1, 0], dtype=int64)

# Байесовская модель

Подсчитывает апостериорное распределение

In [4]:
import numpy as np
from sklearn.mixture import BayesianGaussianMixture
X = np.array([[1, 2], [1, 4], [1, 0], [4, 2], [12, 4], [10, 7]])
bgm = BayesianGaussianMixture(n_components=2, random_state=42).fit(X)
bgm.means_

array([[2.4975536 , 2.29225365],
       [8.45533127, 4.5225831 ]])

In [5]:
bgm.predict([[0, 0], [9, 3]])

array([0, 1], dtype=int64)